### PR TITLE
Minor reference fixes and a dependency

### PR DESCRIPTION
**Pull request by FedeGioz**
There is a typo in the imports. It's written Tts, but the class is TTS. Additionally SciPy requires numpy, i added the latest version to the requirements. Thanks for the project <3

### CODE REVIEW

**Comment by FedeGioz** [comment]
This is an actual issue, i ran it from the root dir, not src

**Comment by FedeGioz** [comment]
The file is called TTS.py

**Comment by FujiwaraChoki** [comment]
image

**Comment by FedeGioz** [comment]
Strange, the github version is different from your local, look at the file on github.
image

**Comment by FujiwaraChoki** [comment]
That is so weird, thank you for pointing this out! Can you make a PR renaming the file to Tts.py? As there's already a module called TTS (CoquiTTS).

**Pull request closed without merging**
