### PR TITLE
Fix TTS mispelling that broke main.py

### PR DESCRIPTION
**Pull request by WaterPheonix196**
tiny change to fix the main.py

### CODE REVIEW

**Comment by FujiwaraChoki** [comment]
The file is called `Tts.py`, not `TTS.py`. `TTS` is the class name, I assume you mixed that up.

**Comment by WaterPheonix196** [comment]
Hmm. When I ran for first time, it told me it doesnt exist

**Comment by FujiwaraChoki** [comment]
You need to run `python src/main.py` from the root directory, not the `src` directory, I think that was your problem.

**Comment by WaterPheonix196** [comment]
No I ran it from C:\Users\fitzg\OneDrive\Desktop\MoneyPrinterV2.

**Comment by FujiwaraChoki** [comment]
Okay that's very weird, sorry no idea what the problem is :(

**Pull request closed without merging**
